services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: gallery-epoque-pocketbase
    restart: unless-stopped
    command:
      - serve
      - --http=0.0.0.0:8090
      - --dir=/pb_data
      - --migrationsDir=/pb_migrations
      - --publicDir=/pb_public
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_public:/pb_public

  nextjs:
    build:
      context: .
      args:
        NEXT_PUBLIC_POCKETBASE_URL: ${NEXT_PUBLIC_POCKETBASE_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: gallery-epoque-nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - POCKETBASE_SUPERUSER_EMAIL=${POCKETBASE_SUPERUSER_EMAIL}
      - POCKETBASE_SUPERUSER_PASSWORD=${POCKETBASE_SUPERUSER_PASSWORD}
      - NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - pocketbase
